---
name: ((deployment-name))

releases:
- name: concourse
  version: ((concourse-release-version))
- name: garden-runc
  version: ((garden-runc-release-version))
- name: vault
  version: latest

instance_groups:
- name: vault
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  persistent_disk: 10240
  vm_type: topgun
  stemcell: trusty
  jobs:
  - release: vault
    name: vault
    properties: {}

- name: concourse
  instances: ((instances))
  networks: [{name: topgun}]
  azs: [z1]
  persistent_disk: 10240
  vm_type: topgun
  stemcell: trusty
  jobs:
  - release: concourse
    name: atc
    properties:
      no_really_i_dont_want_any_auth: true
      log_level: debug
      postgresql_database: atc
      vault:
        url: ((vault_url))
        ca_cert: ((vault_ca.certificate))
        auth:
          client_token: ((vault_client_token))

  - release: concourse
    name: tsa
    properties: {}

  - release: concourse
    name: postgresql
    properties:
      databases:
      - name: atc
        role: atc
        password: dummy-password

  - release: concourse
    name: groundcrew
    properties:
      # prevent tests from hanging forever
      drain_timeout: 10m

  - release: concourse
    name: baggageclaim
    properties: {}

  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true
        network_mtu: 1460

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

variables:
- name: vault_ca
  type: certificate
  options:
    is_ca: true
    common_name: vaultCA
- name: vault_tls
  type: certificate
  options:
    ca: vault_ca
    common_name: ((vault_ip))
    alternative_names:
    - ((vault_ip))
    extended_key_usage:
    - server_auth
- name: vault_client
  type: certificate
  options:
    ca: vault_ca
    common_name: concourse
    extended_key_usage:
    - client_auth

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
