resource_types:
- name: fake-resource-type
  type: docker-image
  source:
    repository: concourse/time-resource

resources:
- name: fake-resource
  type: fake-resource-type
  source:
    interval: 1s
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAtCS10/f7W7lkQaSgD/mVeaSOvSF9ql4hf/zfMwfVGgHWjj+W
      resource_secret
      DWiJL+OFeg9kawcUL6hQ8JeXPhlImG6RTUffma9+iGQyyBMCGd1l
      -----END RSA PRIVATE KEY-----

jobs:
- name: simple-job
  plan:
  - get: fake-resource
  - task: simple-task
    params:
      SECRET: job_secret
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: busybox}

      params:
        SECRET:

      run:
        path: sh
        args: ['-c', 'echo shhhhhh']
