resource_types:
- name: fake-resource-type
  type: docker-image
  source:
    repository: concourse/time-resource

resources:
- name: fake-resource
  type: fake-resource-type
  source:
    interval: 1s

jobs:
- name: simple-job
  plan:
  - get: fake-resource
  - task: simple-task
    params:
      SECRET: job_secret
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: busybox}

      params:
        SECRET:

      run:
        path: sh
        args: ['-c', 'echo shhhhhh']
